import { Card, Rarity } from "./types";

export const CARD_POOL: Card[] = [
  {
    id: "1",
    name: "Flame Fox",
    rarity: Rarity.COMMON,
    type: "Fire",
    hp: 60,
    description: "A small fox with a tail that glows like a candle.",
    imageUrl: "https://picsum.photos/seed/flamefox/400/600",
  },
  {
    id: "2",
    name: "Aqua Turtle",
    rarity: Rarity.COMMON,
    type: "Water",
    hp: 70,
    description: "It hides in its shell to avoid predators.",
    imageUrl: "https://picsum.photos/seed/aquaturtle/400/600",
  },
  {
    id: "3",
    name: "Leaf Bunny",
    rarity: Rarity.COMMON,
    type: "Grass",
    hp: 50,
    description: "Its ears look like fresh spring leaves.",
    imageUrl: "https://picsum.photos/seed/leafbunny/400/600",
  },
  {
    id: "4",
    name: "Spark Mouse",
    rarity: Rarity.COMMON,
    type: "Electric",
    hp: 40,
    description: "It stores electricity in its cheeks.",
    imageUrl: "https://picsum.photos/seed/sparkmouse/400/600",
  },
  {
    id: "5",
    name: "Shadow Cat",
    rarity: Rarity.UNCOMMON,
    type: "Dark",
    hp: 80,
    description: "It blends perfectly into the night.",
    imageUrl: "https://picsum.photos/seed/shadowcat/400/600",
  },
  {
    id: "6",
    name: "Iron Golem",
    rarity: Rarity.UNCOMMON,
    type: "Steel",
    hp: 120,
    description: "A heavy construct made of ancient metal.",
    imageUrl: "https://picsum.photos/seed/irongolem/400/600",
  },
  {
    id: "7",
    name: "Solar Dragon",
    rarity: Rarity.RARE,
    type: "Dragon",
    hp: 150,
    description: "A legendary dragon that draws power from the sun.",
    imageUrl: "https://picsum.photos/seed/solardragon/400/600",
  },
  {
    id: "8",
    name: "Lunar Phoenix",
    rarity: Rarity.RARE,
    type: "Psychic",
    hp: 130,
    description: "It rises from the ashes under the full moon.",
    imageUrl: "https://picsum.photos/seed/lunarphoenix/400/600",
  },
  {
    id: "9",
    name: "Cosmic Whale",
    rarity: Rarity.ULTRA_RARE,
    type: "Water",
    hp: 200,
    description: "A giant creature that swims through the stars.",
    imageUrl: "https://picsum.photos/seed/cosmicwhale/400/600",
  },
  {
    id: "10",
    name: "Void Reaper",
    rarity: Rarity.SECRET_RARE,
    type: "Dark",
    hp: 180,
    description: "A mysterious entity from the edge of the universe.",
    imageUrl: "https://picsum.photos/seed/voidreaper/400/600",
  },
  {
    id: "11",
    name: "Thunder Hawk",
    rarity: Rarity.UNCOMMON,
    type: "Electric",
    hp: 90,
    description: "Its wings create thunderclaps when it dives.",
    imageUrl: "https://picsum.photos/seed/thunderhawk/400/600",
  },
  {
    id: "12",
    name: "Stone Titan",
    rarity: Rarity.UNCOMMON,
    type: "Fighting",
    hp: 140,
    description: "A mountain that came to life.",
    imageUrl: "https://picsum.photos/seed/stonetitan/400/600",
  },
  {
    id: "13",
    name: "Crystal Deer",
    rarity: Rarity.RARE,
    type: "Psychic",
    hp: 110,
    description: "Its antlers are made of pure diamond.",
    imageUrl: "https://picsum.photos/seed/crystaldeer/400/600",
  },
  {
    id: "14",
    name: "Magma Core",
    rarity: Rarity.RARE,
    type: "Fire",
    hp: 160,
    description: "The living heart of a volcano.",
    imageUrl: "https://picsum.photos/seed/magmacore/400/600",
  },
  {
    id: "15",
    name: "Wind Spirit",
    rarity: Rarity.COMMON,
    type: "Normal",
    hp: 40,
    description: "A gentle breeze that took form.",
    imageUrl: "https://picsum.photos/seed/windspirit/400/600",
  },
  {
    id: "16",
    name: "Frost Owl",
    rarity: Rarity.UNCOMMON,
    type: "Water",
    hp: 80,
    description: "Its feathers are as cold as ice.",
    imageUrl: "https://picsum.photos/seed/frostowl/400/600",
  },
  {
    id: "17",
    name: "Earth Golem",
    rarity: Rarity.COMMON,
    type: "Fighting",
    hp: 100,
    description: "A sturdy guardian made of clay and stone.",
    imageUrl: "https://picsum.photos/seed/earthgolem/400/600",
  },
  {
    id: "18",
    name: "Star Sprite",
    rarity: Rarity.RARE,
    type: "Psychic",
    hp: 60,
    description: "It fell from a shooting star.",
    imageUrl: "https://picsum.photos/seed/starsprite/400/600",
  },
  {
    id: "19",
    name: "Abyssal Serpent",
    rarity: Rarity.ULTRA_RARE,
    type: "Dragon",
    hp: 190,
    description: "It dwells in the deepest parts of the ocean.",
    imageUrl: "https://picsum.photos/seed/abyssalserpent/400/600",
  },
  {
    id: "20",
    name: "Golden King",
    rarity: Rarity.SECRET_RARE,
    type: "Steel",
    hp: 250,
    description: "The ruler of a forgotten golden empire.",
    imageUrl: "https://picsum.photos/seed/goldenking/400/600",
  },
];

export const RARITY_CHANCES = {
  [Rarity.COMMON]: 0.6,
  [Rarity.UNCOMMON]: 0.25,
  [Rarity.RARE]: 0.1,
  [Rarity.ULTRA_RARE]: 0.04,
  [Rarity.SECRET_RARE]: 0.01,
};
